version: '3'
services:

  seeder:
    image: italia/daf-metabase-cacher
    volumes:
      - ./config-docker.properties:/etc/config.properties
    command: seeder
    depends_on:
      - "redis"

  worker:
    image: italia/daf-metabase-cacher
    volumes:
      - ./config-docker.properties:/etc/config.properties
    command: worker
    depends_on:
      - "chrome"
      - "redis"
    restart: on-failure

  api:
    image: italia/daf-metabase-cacher
    ports:
     - "4567:4567"
    volumes:
      - ./config-docker.properties:/etc/config.properties
    command: server
    depends_on:
      - "redis"

  redis:
    image: "redis:alpine"

  selenium:
    image: selenium/hub
    ports:
      - "4444:4444"
    environment:
      - GRID_MAX_SESSION=200
      - GRID_BROWSER_TIMEOUT=100000
      - GRID_TIMEOUT=90000
      - GRID_NEW_SESSION_WAIT_TIMEOUT=300000
      - JAVA_OPTS=-Dselenium.LOGGER.level=WARNING


  chrome:
    image: selenium/node-chrome
    links:
      - selenium:selenium
    volumes:
      - /dev/shm:/dev/shm # Mitigates the Chromium issue described at https://code.google.com/p/chromium/issues/detail?id=519952
    environment:
      HUB_PORT_4444_TCP_ADDR: selenium
      HUB_PORT_4444_TCP_PORT: 4444
      NODE_MAX_INSTANCES: 60
      NODE_MAX_SESSION: 60
      JAVA_OPTS: -Dselenium.LOGGER.level=WARNING
